#!/bin/bash
python main.py --scenario task --loss otfl --otfl-alpha 0.5 --metrics --results-dir ./results_regularation
python main.py --scenario task --loss otfl --otfl-alpha 1.0 --metrics --results-dir ./results_regularation
python main.py --scenario task --loss otfl --otfl-alpha 1.5 --metrics --results-dir ./results_regularation
python main.py --scenario task --loss otfl --otfl-alpha 2.0 --metrics --results-dir ./results_regularation
python main.py --scenario task --loss otfl --otfl-alpha 2.5 --metrics --results-dir ./results_regularation
python main.py --scenario task --loss otfl --otfl-alpha 3.0 --metrics --results-dir ./results_regularation
python main.py --scenario task --loss otfl --otfl-alpha 3.5 --metrics --results-dir ./results_regularation
python main.py --scenario task --loss otfl --otfl-alpha 4.0 --metrics --results-dir ./results_regularation
python main.py --scenario task --loss otfl --otfl-alpha 4.5 --metrics --results-dir ./results_regularation
python main.py --scenario task --loss otfl --otfl-alpha 5.0 --metrics --results-dir ./results_regularation
python main.py --scenario task --loss otfl --otfl-alpha 5.5 --metrics --results-dir ./results_regularation
python main.py --scenario task --loss otfl --otfl-alpha 6.0 --metrics --results-dir ./results_regularation
python main.py --scenario task --loss otfl --otfl-alpha 6.5 --metrics --results-dir ./results_regularation
python main.py --scenario task --loss otfl --otfl-alpha 7.0 --metrics --results-dir ./results_regularation
python main.py --scenario task --loss otfl --otfl-alpha 7.5 --metrics --results-dir ./results_regularation
python main.py --scenario task --loss otfl --otfl-alpha 8.0 --metrics --results-dir ./results_regularation
python main.py --scenario task --loss otfl --otfl-alpha 8.5 --metrics --results-dir ./results_regularation
python main.py --scenario task --loss otfl --otfl-alpha 9.0 --metrics --results-dir ./results_regularation
python main.py --scenario task --loss otfl --otfl-alpha 9.5 --metrics --results-dir ./results_regularation
python main.py --scenario task --loss otfl --otfl-alpha 10.0 --metrics --results-dir ./results_regularation
python main.py --scenario domain --loss otfl --otfl-alpha 0.5 --metrics --results-dir ./results_regularation
python main.py --scenario domain --loss otfl --otfl-alpha 1.0 --metrics --results-dir ./results_regularation
python main.py --scenario domain --loss otfl --otfl-alpha 1.5 --metrics --results-dir ./results_regularation
python main.py --scenario domain --loss otfl --otfl-alpha 2.0 --metrics --results-dir ./results_regularation
python main.py --scenario domain --loss otfl --otfl-alpha 2.5 --metrics --results-dir ./results_regularation
python main.py --scenario domain --loss otfl --otfl-alpha 3.0 --metrics --results-dir ./results_regularation
python main.py --scenario domain --loss otfl --otfl-alpha 3.5 --metrics --results-dir ./results_regularation
python main.py --scenario domain --loss otfl --otfl-alpha 4.0 --metrics --results-dir ./results_regularation
python main.py --scenario domain --loss otfl --otfl-alpha 4.5 --metrics --results-dir ./results_regularation
python main.py --scenario domain --loss otfl --otfl-alpha 5.0 --metrics --results-dir ./results_regularation
python main.py --scenario domain --loss otfl --otfl-alpha 5.5 --metrics --results-dir ./results_regularation
python main.py --scenario domain --loss otfl --otfl-alpha 6.0 --metrics --results-dir ./results_regularation
python main.py --scenario domain --loss otfl --otfl-alpha 6.5 --metrics --results-dir ./results_regularation
python main.py --scenario domain --loss otfl --otfl-alpha 7.0 --metrics --results-dir ./results_regularation
python main.py --scenario domain --loss otfl --otfl-alpha 7.5 --metrics --results-dir ./results_regularation
python main.py --scenario domain --loss otfl --otfl-alpha 8.0 --metrics --results-dir ./results_regularation
python main.py --scenario domain --loss otfl --otfl-alpha 8.5 --metrics --results-dir ./results_regularation
python main.py --scenario domain --loss otfl --otfl-alpha 9.0 --metrics --results-dir ./results_regularation
python main.py --scenario domain --loss otfl --otfl-alpha 9.5 --metrics --results-dir ./results_regularation
python main.py --scenario domain --loss otfl --otfl-alpha 10.0 --metrics --results-dir ./results_regularation
python main.py --scenario class --loss otfl --otfl-alpha 0.5 --metrics --results-dir ./results_regularation
python main.py --scenario class --loss otfl --otfl-alpha 1.0 --metrics --results-dir ./results_regularation
python main.py --scenario class --loss otfl --otfl-alpha 1.5 --metrics --results-dir ./results_regularation
python main.py --scenario class --loss otfl --otfl-alpha 2.0 --metrics --results-dir ./results_regularation
python main.py --scenario class --loss otfl --otfl-alpha 2.5 --metrics --results-dir ./results_regularation
python main.py --scenario class --loss otfl --otfl-alpha 3.0 --metrics --results-dir ./results_regularation
python main.py --scenario class --loss otfl --otfl-alpha 3.5 --metrics --results-dir ./results_regularation
python main.py --scenario class --loss otfl --otfl-alpha 4.0 --metrics --results-dir ./results_regularation
python main.py --scenario class --loss otfl --otfl-alpha 4.5 --metrics --results-dir ./results_regularation
python main.py --scenario class --loss otfl --otfl-alpha 5.0 --metrics --results-dir ./results_regularation
python main.py --scenario class --loss otfl --otfl-alpha 5.5 --metrics --results-dir ./results_regularation
python main.py --scenario class --loss otfl --otfl-alpha 6.0 --metrics --results-dir ./results_regularation
python main.py --scenario class --loss otfl --otfl-alpha 6.5 --metrics --results-dir ./results_regularation
python main.py --scenario class --loss otfl --otfl-alpha 7.0 --metrics --results-dir ./results_regularation
python main.py --scenario class --loss otfl --otfl-alpha 7.5 --metrics --results-dir ./results_regularation
python main.py --scenario class --loss otfl --otfl-alpha 8.0 --metrics --results-dir ./results_regularation
python main.py --scenario class --loss otfl --otfl-alpha 8.5 --metrics --results-dir ./results_regularation
python main.py --scenario class --loss otfl --otfl-alpha 9.0 --metrics --results-dir ./results_regularation
python main.py --scenario class --loss otfl --otfl-alpha 9.5 --metrics --results-dir ./results_regularation
python main.py --scenario class --loss otfl --otfl-alpha 10.0 --metrics --results-dir ./results_regularation
